# Generated by Django 4.0.4 on 2022-05-04 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('formations', models.TextField()),
                ('competances', models.TextField()),
                ('langues', models.TextField()),
                ('certificats', models.TextField()),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
