# Generated by Django 4.0.4 on 2022-05-05 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruteur', '0016_alter_recruteur_secteur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demandeur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('vu', models.BooleanField(default=False)),
                ('etat', models.BooleanField(blank=True, null=True)),
                ('dem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ofr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruteur.offre')),
            ],
        ),
    ]
