# Generated by Django 4.0.4 on 2022-05-05 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandeur', '0002_demande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='dem',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='ofr',
        ),
    ]
