# Generated by Django 4.0.4 on 2022-05-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandeur', '0004_demande_dem_demande_ofr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demande',
            options={'ordering': ['-date_demande', '-id']},
        ),
        migrations.AddField(
            model_name='cv',
            name='cin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='sexe',
            field=models.CharField(default='Male', max_length=10),
        ),
    ]
