# Generated by Django 4.0.4 on 2022-05-03 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruteur', '0002_delete_recruteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='recruteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=50)),
                ('secteur', models.CharField(choices=[('Agroalimentaire', 'Agroalimentaire'), ('Banque', 'Banque / Assurance'), ('Bois', 'Bois / Papier / Carton / Imprimerie'), ('BTP', 'BTP / Matériaux de construction'), ('Chimie', 'Chimie / Parachimie'), ('Commerce', 'Commerce / Négoce / Distribution'), ('Édition', 'Édition / Communication / Multimédia'), ('Électronique', 'Électronique / Électricité'), ('Études', 'Études et conseils'), ('Pharmaceutique', 'Industrie pharmaceutique'), ('Informatique', 'Informatique / Télécoms'), ('Machines', 'Machines et équipements / Automobile'), ('Métallurgie', 'Métallurgie / Travail du métal'), ('Plastique', 'Plastique / Caoutchouc'), ('Services', 'Services aux entreprises'), ('Textile', 'Textile / Habillement / Chaussure'), ('Transports', 'Transports / Logistique')], max_length=50)),
                ('logo', models.ImageField(upload_to='logos/%Y/%m/%d/')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
