# Generated by Django 4.0.4 on 2022-05-04 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruteur', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_offre', models.DateField(auto_now_add=True)),
                ('titre', models.CharField(max_length=100)),
                ('experiences', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('details', models.TextField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
