# Generated by Django 4.0.4 on 2022-05-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruteur', '0004_offre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offre',
            options={'ordering': ['-date_offre', '-id']},
        ),
        migrations.AddField(
            model_name='offre',
            name='email',
            field=models.CharField(default='abc@abc.abc', max_length=50),
        ),
    ]
