# Generated by Django 4.0.4 on 2022-05-04 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruteur', '0008_alter_offre_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='offre',
            name='rec',
            field=models.OneToOneField(blank=True, default=22, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruteur.recruteur'),
        ),
    ]
