# Generated by Django 4.0.4 on 2022-05-04 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruteur', '0009_remove_offre_utilisateur_offre_rec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='rec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruteur.recruteur'),
        ),
    ]
