# Generated by Django 4.0.4 on 2022-05-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruteur', '0015_alter_recruteur_secteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruteur',
            name='secteur',
            field=models.CharField(choices=[('Agroalimentaire', 'Agroalimentaire'), ('Banque / Assurance', 'Banque / Assurance'), ('Bois / Papier / Carton / Imprimerie', 'Bois / Papier / Carton / Imprimerie'), ('BTP / Matériaux de construction', 'BTP / Matériaux de construction'), ('Chimie / Parachimie', 'Chimie / Parachimie'), ('Commerce / Négoce / Distribution', 'Commerce / Négoce / Distribution'), ('Édition / Communication / Multimédia', 'Édition / Communication / Multimédia'), ('Électronique / Électricité', 'Électronique / Électricité'), ('Études et conseils', 'Études et conseils'), ('Industrie pharmaceutique', 'Industrie pharmaceutique'), ('Informatique / Télécoms', 'Informatique / Télécoms'), ('Machines et équipements / Automobile', 'Machines et équipements / Automobile'), ('Métallurgie / Travail du métal', 'Métallurgie / Travail du métal'), ('Plastique / Caoutchouc', 'Plastique / Caoutchouc'), ('Services aux entreprises', 'Services aux entreprises'), ('Textile / Habillement / Chaussure', 'Textile / Habillement / Chaussure'), ('Transports', 'Textile / Habillement / Chaussure')], max_length=50),
        ),
    ]
