# Generated by Django 4.0.4 on 2022-05-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruteur', '0016_alter_recruteur_secteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruteur',
            name='secteur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
