# Generated by Django 4.0.4 on 2022-05-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruteur', '0018_alter_recruteur_secteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='date_limite',
            field=models.DateField(null=True),
        ),
    ]
