# Generated by Django 4.0.4 on 2022-05-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruteur', '0019_offre_date_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
